
/** Decode HTML entities in the string, e.g. &amp; or &#x3C;. */
fun decodeHTMLEntities(str: String): String {
    return htmlEntityMatch.replace(str) {
        val value = it.groupValues[1]
        when {
            value.startsWith("#x") || value.startsWith("#X") ->
                value.substring(2).toInt(16).toChar().toString()
            value.startsWith("#") ->
                value.substring(1).toInt(10).toChar().toString()
            else -> htmlEntities[value] ?: it.value
        }
    }
}



private val htmlEntityMatch = Regex("&(#[0-9]+|#[xX][0-9a-zA-Z]+|[a-zA-Z]+);")

private val htmlEntities = mapOf(
    "AElig" to "Æ",
    "AMP" to "&",
    "Aacute" to "Á",
    "Abreve" to "Ă",
    "Acirc" to "Â",
    "Acy" to "А",
    "Afr" to "𝔄",
    "Agrave" to "À",
    "Alpha" to "Α",
    "Amacr" to "Ā",
    "And" to "⩓",
    "Aogon" to "Ą",
    "Aopf" to "𝔸",
    "ApplyFunction" to "⁡",
    "Aring" to "Å",
    "Ascr" to "𝒜",
    "Assign" to "≔",
    "Atilde" to "Ã",
    "Auml" to "Ä",
    "Backslash" to "∖",
    "Barv" to "⫧",
    "Barwed" to "⌆",
    "Bcy" to "Б",
    "Because" to "∵",
    "Bernoullis" to "ℬ",
    "Beta" to "Β",
    "Bfr" to "𝔅",
    "Bopf" to "𝔹",
    "Breve" to "˘",
    "Bscr" to "ℬ",
    "Bumpeq" to "≎",
    "CHcy" to "Ч",
    "COPY" to "©",
    "Cacute" to "Ć",
    "Cap" to "⋒",
    "CapitalDifferentialD" to "ⅅ",
    "Cayleys" to "ℭ",
    "Ccaron" to "Č",
    "Ccedil" to "Ç",
    "Ccirc" to "Ĉ",
    "Cconint" to "∰",
    "Cdot" to "Ċ",
    "Cedilla" to "¸",
    "CenterDot" to "·",
    "Cfr" to "ℭ",
    "Chi" to "Χ",
    "CircleDot" to "⊙",
    "CircleMinus" to "⊖",
    "CirclePlus" to "⊕",
    "CircleTimes" to "⊗",
    "ClockwiseContourIntegral" to "∲",
    "CloseCurlyDoubleQuote" to "”",
    "CloseCurlyQuote" to "’",
    "Colon" to "∷",
    "Colone" to "⩴",
    "Congruent" to "≡",
    "Conint" to "∯",
    "ContourIntegral" to "∮",
    "Copf" to "ℂ",
    "Coproduct" to "∐",
    "CounterClockwiseContourIntegral" to "∳",
    "Cross" to "⨯",
    "Cscr" to "𝒞",
    "Cup" to "⋓",
    "CupCap" to "≍",
    "DD" to "ⅅ",
    "DDotrahd" to "⤑",
    "DJcy" to "Ђ",
    "DScy" to "Ѕ",
    "DZcy" to "Џ",
    "Dagger" to "‡",
    "Darr" to "↡",
    "Dashv" to "⫤",
    "Dcaron" to "Ď",
    "Dcy" to "Д",
    "Del" to "∇",
    "Delta" to "Δ",
    "Dfr" to "𝔇",
    "DiacriticalAcute" to "´",
    "DiacriticalDot" to "˙",
    "DiacriticalDoubleAcute" to "˝",
    "DiacriticalGrave" to "`",
    "DiacriticalTilde" to "˜",
    "Diamond" to "⋄",
    "DifferentialD" to "ⅆ",
    "Dopf" to "𝔻",
    "Dot" to "¨",
    "DotDot" to "\u20DC",
    "DotEqual" to "≐",
    "DoubleContourIntegral" to "∯",
    "DoubleDot" to "¨",
    "DoubleDownArrow" to "⇓",
    "DoubleLeftArrow" to "⇐",
    "DoubleLeftRightArrow" to "⇔",
    "DoubleLeftTee" to "⫤",
    "DoubleLongLeftArrow" to "⟸",
    "DoubleLongLeftRightArrow" to "⟺",
    "DoubleLongRightArrow" to "⟹",
    "DoubleRightArrow" to "⇒",
    "DoubleRightTee" to "⊨",
    "DoubleUpArrow" to "⇑",
    "DoubleUpDownArrow" to "⇕",
    "DoubleVerticalBar" to "∥",
    "DownArrow" to "↓",
    "DownArrowBar" to "⤓",
    "DownArrowUpArrow" to "⇵",
    "DownBreve" to "\u0311 ",
    "DownLeftRightVector" to "⥐",
    "DownLeftTeeVector" to "⥞",
    "DownLeftVector" to "↽",
    "DownLeftVectorBar" to "⥖",
    "DownRightTeeVector" to "⥟",
    "DownRightVector" to "⇁",
    "DownRightVectorBar" to "⥗",
    "DownTee" to "⊤",
    "DownTeeArrow" to "↧",
    "Downarrow" to "⇓",
    "Dscr" to "𝒟",
    "Dstrok" to "Đ",
    "ENG" to "Ŋ",
    "ETH" to "Ð",
    "Eacute" to "É",
    "Ecaron" to "Ě",
    "Ecirc" to "Ê",
    "Ecy" to "Э",
    "Edot" to "Ė",
    "Efr" to "𝔈",
    "Egrave" to "È",
    "Element" to "∈",
    "Emacr" to "Ē",
    "EmptySmallSquare" to "◻",
    "EmptyVerySmallSquare" to "▫",
    "Eogon" to "Ę",
    "Eopf" to "𝔼",
    "Epsilon" to "Ε",
    "Equal" to "⩵",
    "EqualTilde" to "≂",
    "Equilibrium" to "⇌",
    "Escr" to "ℰ",
    "Esim" to "⩳",
    "Eta" to "Η",
    "Euml" to "Ë",
    "Exists" to "∃",
    "ExponentialE" to "ⅇ",
    "Fcy" to "Ф",
    "Ffr" to "𝔉",
    "FilledSmallSquare" to "◼",
    "FilledVerySmallSquare" to "▪",
    "Fopf" to "𝔽",
    "ForAll" to "∀",
    "Fouriertrf" to "ℱ",
    "Fscr" to "ℱ",
    "GJcy" to "Ѓ",
    "GT" to ">",
    "Gamma" to "Γ",
    "Gammad" to "Ϝ",
    "Gbreve" to "Ğ",
    "Gcedil" to "Ģ",
    "Gcirc" to "Ĝ",
    "Gcy" to "Г",
    "Gdot" to "Ġ",
    "Gfr" to "𝔊",
    "Gg" to "⋙",
    "Gopf" to "𝔾",
    "GreaterEqual" to "≥",
    "GreaterEqualLess" to "⋛",
    "GreaterFullEqual" to "≧",
    "GreaterGreater" to "⪢",
    "GreaterLess" to "≷",
    "GreaterSlantEqual" to "⩾",
    "GreaterTilde" to "≳",
    "Gscr" to "𝒢",
    "Gt" to "≫",
    "HARDcy" to "Ъ",
    "Hacek" to "ˇ",
    "Hat" to "^",
    "Hcirc" to "Ĥ",
    "Hfr" to "ℌ",
    "HilbertSpace" to "ℋ",
    "Hopf" to "ℍ",
    "HorizontalLine" to "─",
    "Hscr" to "ℋ",
    "Hstrok" to "Ħ",
    "HumpDownHump" to "≎",
    "HumpEqual" to "≏",
    "IEcy" to "Е",
    "IJlig" to "Ĳ",
    "IOcy" to "Ё",
    "Iacute" to "Í",
    "Icirc" to "Î",
    "Icy" to "И",
    "Idot" to "İ",
    "Ifr" to "ℑ",
    "Igrave" to "Ì",
    "Im" to "ℑ",
    "Imacr" to "Ī",
    "ImaginaryI" to "ⅈ",
    "Implies" to "⇒",
    "Int" to "∬",
    "Integral" to "∫",
    "Intersection" to "⋂",
    "InvisibleComma" to "⁣",
    "InvisibleTimes" to "⁢",
    "Iogon" to "Į",
    "Iopf" to "𝕀",
    "Iota" to "Ι",
    "Iscr" to "ℐ",
    "Itilde" to "Ĩ",
    "Iukcy" to "І",
    "Iuml" to "Ï",
    "Jcirc" to "Ĵ",
    "Jcy" to "Й",
    "Jfr" to "𝔍",
    "Jopf" to "𝕁",
    "Jscr" to "𝒥",
    "Jsercy" to "Ј",
    "Jukcy" to "Є",
    "KHcy" to "Х",
    "KJcy" to "Ќ",
    "Kappa" to "Κ",
    "Kcedil" to "Ķ",
    "Kcy" to "К",
    "Kfr" to "𝔎",
    "Kopf" to "𝕂",
    "Kscr" to "𝒦",
    "LJcy" to "Љ",
    "LT" to "<",
    "Lacute" to "Ĺ",
    "Lambda" to "Λ",
    "Lang" to "⟪",
    "Laplacetrf" to "ℒ",
    "Larr" to "↞",
    "Lcaron" to "Ľ",
    "Lcedil" to "Ļ",
    "Lcy" to "Л",
    "LeftAngleBracket" to "〈",
    "LeftArrow" to "←",
    "LeftArrowBar" to "⇤",
    "LeftArrowRightArrow" to "⇆",
    "LeftCeiling" to "⌈",
    "LeftDoubleBracket" to "⟦",
    "LeftDownTeeVector" to "⥡",
    "LeftDownVector" to "⇃",
    "LeftDownVectorBar" to "⥙",
    "LeftFloor" to "⌊",
    "LeftRightArrow" to "↔",
    "LeftRightVector" to "⥎",
    "LeftTee" to "⊣",
    "LeftTeeArrow" to "↤",
    "LeftTeeVector" to "⥚",
    "LeftTriangle" to "⊲",
    "LeftTriangleBar" to "⧏",
    "LeftTriangleEqual" to "⊴",
    "LeftUpDownVector" to "⥑",
    "LeftUpTeeVector" to "⥠",
    "LeftUpVector" to "↿",
    "LeftUpVectorBar" to "⥘",
    "LeftVector" to "↼",
    "LeftVectorBar" to "⥒",
    "Leftarrow" to "⇐",
    "Leftrightarrow" to "⇔",
    "LessEqualGreater" to "⋚",
    "LessFullEqual" to "≦",
    "LessGreater" to "≶",
    "LessLess" to "⪡",
    "LessSlantEqual" to "⩽",
    "LessTilde" to "≲",
    "Lfr" to "𝔏",
    "Ll" to "⋘",
    "Lleftarrow" to "⇚",
    "Lmidot" to "Ŀ",
    "LongLeftArrow" to "⟵",
    "LongLeftRightArrow" to "⟷",
    "LongRightArrow" to "⟶",
    "Longleftarrow" to "⟸",
    "Longleftrightarrow" to "⟺",
    "Longrightarrow" to "⟹",
    "Lopf" to "𝕃",
    "LowerLeftArrow" to "↙",
    "LowerRightArrow" to "↘",
    "Lscr" to "ℒ",
    "Lsh" to "↰",
    "Lstrok" to "Ł",
    "Lt" to "≪",
    "Map" to "⤅",
    "Mcy" to "М",
    "MediumSpace" to " ",
    "Mellintrf" to "ℳ",
    "Mfr" to "𝔐",
    "MinusPlus" to "∓",
    "Mopf" to "𝕄",
    "Mscr" to "ℳ",
    "Mu" to "Μ",
    "NJcy" to "Њ",
    "Nacute" to "Ń",
    "Ncaron" to "Ň",
    "Ncedil" to "Ņ",
    "Ncy" to "Н",
    "NegativeMediumSpace" to "​",
    "NegativeThickSpace" to "​",
    "NegativeThinSpace" to "​",
    "NegativeVeryThinSpace" to "​",
    "NestedGreaterGreater" to "≫",
    "NestedLessLess" to "≪",
    "NewLine" to "␊",
    "Nfr" to "𝔑",
    "NoBreak" to "⁠",
    "NonBreakingSpace" to "\u00A0",
    "Nopf" to "ℕ",
    "Not" to "⫬",
    "NotCongruent" to "≢",
    "NotCupCap" to "≭",
    "NotDoubleVerticalBar" to "∦",
    "NotElement" to "∉",
    "NotEqual" to "≠",
    "NotEqualTilde" to "≂̸",
    "NotExists" to "∄",
    "NotGreater" to "≯",
    "NotGreaterEqual" to "≱",
    "NotGreaterFullEqual" to "≧̸",
    "NotGreaterGreater" to "≫̸",
    "NotGreaterLess" to "≹",
    "NotGreaterSlantEqual" to "⩾̸",
    "NotGreaterTilde" to "≵",
    "NotHumpDownHump" to "≎̸",
    "NotHumpEqual" to "≏̸",
    "NotLeftTriangle" to "⋪",
    "NotLeftTriangleBar" to "⧏̸",
    "NotLeftTriangleEqual" to "⋬",
    "NotLess" to "≮",
    "NotLessEqual" to "≰",
    "NotLessGreater" to "≸",
    "NotLessLess" to "≪̸",
    "NotLessSlantEqual" to "⩽̸",
    "NotLessTilde" to "≴",
    "NotNestedGreaterGreater" to "⪢̸",
    "NotNestedLessLess" to "⪡̸",
    "NotPrecedes" to "⊀",
    "NotPrecedesEqual" to "⪯̸",
    "NotPrecedesSlantEqual" to "⋠",
    "NotReverseElement" to "∌",
    "NotRightTriangle" to "⋫",
    "NotRightTriangleBar" to "⧐̸",
    "NotRightTriangleEqual" to "⋭",
    "NotSquareSubset" to "⊏̸",
    "NotSquareSubsetEqual" to "⋢",
    "NotSquareSuperset" to "⊐̸",
    "NotSquareSupersetEqual" to "⋣",
    "NotSubset" to "⊂⃒",
    "NotSubsetEqual" to "⊈",
    "NotSucceeds" to "⊁",
    "NotSucceedsEqual" to "⪰̸",
    "NotSucceedsSlantEqual" to "⋡",
    "NotSucceedsTilde" to "≿̸",
    "NotSuperset" to "⊃⃒",
    "NotSupersetEqual" to "⊉",
    "NotTilde" to "≁",
    "NotTildeEqual" to "≄",
    "NotTildeFullEqual" to "≇",
    "NotTildeTilde" to "≉",
    "NotVerticalBar" to "∤",
    "Nscr" to "𝒩",
    "Ntilde" to "Ñ",
    "Nu" to "Ν",
    "OElig" to "Œ",
    "Oacute" to "Ó",
    "Ocirc" to "Ô",
    "Ocy" to "О",
    "Odblac" to "Ő",
    "Ofr" to "𝔒",
    "Ograve" to "Ò",
    "Omacr" to "Ō",
    "Omega" to "Ω",
    "Omicron" to "Ο",
    "Oopf" to "𝕆",
    "OpenCurlyDoubleQuote" to "“",
    "OpenCurlyQuote" to "‘",
    "Or" to "⩔",
    "Oscr" to "𝒪",
    "Oslash" to "Ø",
    "Otilde" to "Õ",
    "Otimes" to "⨷",
    "Ouml" to "Ö",
    "OverBar" to "‾",
    "OverBrace" to "⏞",
    "OverBracket" to "⎴",
    "OverParenthesis" to "⏜",
    "PartialD" to "∂",
    "Pcy" to "П",
    "Pfr" to "𝔓",
    "Phi" to "Φ",
    "Pi" to "Π",
    "PlusMinus" to "±",
    "Poincareplane" to "ℌ",
    "Popf" to "ℙ",
    "Pr" to "⪻",
    "Precedes" to "≺",
    "PrecedesEqual" to "⪯",
    "PrecedesSlantEqual" to "≼",
    "PrecedesTilde" to "≾",
    "Prime" to "″",
    "Product" to "∏",
    "Proportion" to "∷",
    "Proportional" to "∝",
    "Pscr" to "𝒫",
    "Psi" to "Ψ",
    "QUOT" to "\"",
    "Qfr" to "𝔔",
    "Qopf" to "ℚ",
    "Qscr" to "𝒬",
    "RBarr" to "⤐",
    "REG" to "®",
    "Racute" to "Ŕ",
    "Rang" to "⟫",
    "Rarr" to "↠",
    "Rarrtl" to "⤖",
    "Rcaron" to "Ř",
    "Rcedil" to "Ŗ",
    "Rcy" to "Р",
    "Re" to "ℜ",
    "ReverseElement" to "∋",
    "ReverseEquilibrium" to "⇋",
    "ReverseUpEquilibrium" to "⥯",
    "Rfr" to "ℜ",
    "Rho" to "Ρ",
    "RightAngleBracket" to "〉",
    "RightArrow" to "→",
    "RightArrowBar" to "⇥",
    "RightArrowLeftArrow" to "⇄",
    "RightCeiling" to "⌉",
    "RightDoubleBracket" to "⟧",
    "RightDownTeeVector" to "⥝",
    "RightDownVector" to "⇂",
    "RightDownVectorBar" to "⥕",
    "RightFloor" to "⌋",
    "RightTee" to "⊢",
    "RightTeeArrow" to "↦",
    "RightTeeVector" to "⥛",
    "RightTriangle" to "⊳",
    "RightTriangleBar" to "⧐",
    "RightTriangleEqual" to "⊵",
    "RightUpDownVector" to "⥏",
    "RightUpTeeVector" to "⥜",
    "RightUpVector" to "↾",
    "RightUpVectorBar" to "⥔",
    "RightVector" to "⇀",
    "RightVectorBar" to "⥓",
    "Rightarrow" to "⇒",
    "Ropf" to "ℝ",
    "RoundImplies" to "⥰",
    "Rrightarrow" to "⇛",
    "Rscr" to "ℛ",
    "Rsh" to "↱",
    "RuleDelayed" to "⧴",
    "SHCHcy" to "Щ",
    "SHcy" to "Ш",
    "SOFTcy" to "Ь",
    "Sacute" to "Ś",
    "Sc" to "⪼",
    "Scaron" to "Š",
    "Scedil" to "Ş",
    "Scirc" to "Ŝ",
    "Scy" to "С",
    "Sfr" to "𝔖",
    "ShortDownArrow" to "↓",
    "ShortLeftArrow" to "←",
    "ShortRightArrow" to "→",
    "ShortUpArrow" to "↑",
    "Sigma" to "Σ",
    "SmallCircle" to "∘",
    "Sopf" to "𝕊",
    "Sqrt" to "√",
    "Square" to "□",
    "SquareIntersection" to "⊓",
    "SquareSubset" to "⊏",
    "SquareSubsetEqual" to "⊑",
    "SquareSuperset" to "⊐",
    "SquareSupersetEqual" to "⊒",
    "SquareUnion" to "⊔",
    "Sscr" to "𝒮",
    "Star" to "⋆",
    "Sub" to "⋐",
    "Subset" to "⋐",
    "SubsetEqual" to "⊆",
    "Succeeds" to "≻",
    "SucceedsEqual" to "⪰",
    "SucceedsSlantEqual" to "≽",
    "SucceedsTilde" to "≿",
    "SuchThat" to "∋",
    "Sum" to "∑",
    "Sup" to "⋑",
    "Superset" to "⊃",
    "SupersetEqual" to "⊇",
    "Supset" to "⋑",
    "THORN" to "Þ",
    "TRADE" to "™",
    "TSHcy" to "Ћ",
    "TScy" to "Ц",
    "Tab" to "␉",
    "Tau" to "Τ",
    "Tcaron" to "Ť",
    "Tcedil" to "Ţ",
    "Tcy" to "Т",
    "Tfr" to "𝔗",
    "Therefore" to "∴",
    "Theta" to "Θ",
    "ThickSpace" to "  ",
    "ThinSpace" to " ",
    "Tilde" to "∼",
    "TildeEqual" to "≃",
    "TildeFullEqual" to "≅",
    "TildeTilde" to "≈",
    "Topf" to "𝕋",
    "TripleDot" to "\u20DB",
    "Tscr" to "𝒯",
    "Tstrok" to "Ŧ",
    "Uacute" to "Ú",
    "Uarr" to "↟",
    "Uarrocir" to "⥉",
    "Ubrcy" to "Ў",
    "Ubreve" to "Ŭ",
    "Ucirc" to "Û",
    "Ucy" to "У",
    "Udblac" to "Ű",
    "Ufr" to "𝔘",
    "Ugrave" to "Ù",
    "Umacr" to "Ū",
    "UnderBar" to "_",
    "UnderBrace" to "⏟",
    "UnderBracket" to "⎵",
    "UnderParenthesis" to "⏝",
    "Union" to "⋃",
    "UnionPlus" to "⊎",
    "Uogon" to "Ų",
    "Uopf" to "𝕌",
    "UpArrow" to "↑",
    "UpArrowBar" to "⤒",
    "UpArrowDownArrow" to "⇅",
    "UpDownArrow" to "↕",
    "UpEquilibrium" to "⥮",
    "UpTee" to "⊥",
    "UpTeeArrow" to "↥",
    "Uparrow" to "⇑",
    "Updownarrow" to "⇕",
    "UpperLeftArrow" to "↖",
    "UpperRightArrow" to "↗",
    "Upsi" to "ϒ",
    "Upsilon" to "Υ",
    "Uring" to "Ů",
    "Uscr" to "𝒰",
    "Utilde" to "Ũ",
    "Uuml" to "Ü",
    "VDash" to "⊫",
    "Vbar" to "⫫",
    "Vcy" to "В",
    "Vdash" to "⊩",
    "Vdashl" to "⫦",
    "Vee" to "⋁",
    "Verbar" to "‖",
    "Vert" to "‖",
    "VerticalBar" to "∣",
    "VerticalLine" to "|",
    "VerticalSeparator" to "❘",
    "VerticalTilde" to "≀",
    "VeryThinSpace" to " ",
    "Vfr" to "𝔙",
    "Vopf" to "𝕍",
    "Vscr" to "𝒱",
    "Vvdash" to "⊪",
    "Wcirc" to "Ŵ",
    "Wedge" to "⋀",
    "Wfr" to "𝔚",
    "Wopf" to "𝕎",
    "Wscr" to "𝒲",
    "Xfr" to "𝔛",
    "Xi" to "Ξ",
    "Xopf" to "𝕏",
    "Xscr" to "𝒳",
    "YAcy" to "Я",
    "YIcy" to "Ї",
    "YUcy" to "Ю",
    "Yacute" to "Ý",
    "Ycirc" to "Ŷ",
    "Ycy" to "Ы",
    "Yfr" to "𝔜",
    "Yopf" to "𝕐",
    "Yscr" to "𝒴",
    "Yuml" to "Ÿ",
    "ZHcy" to "Ж",
    "Zacute" to "Ź",
    "Zcaron" to "Ž",
    "Zcy" to "З",
    "Zdot" to "Ż",
    "ZeroWidthSpace" to "​",
    "Zeta" to "Ζ",
    "Zfr" to "ℨ",
    "Zopf" to "ℤ",
    "Zscr" to "𝒵",
    "aacute" to "á",
    "abreve" to "ă",
    "ac" to "∾",
    "acE" to "∾̳",
    "acd" to "∿",
    "acirc" to "â",
    "acute" to "´",
    "acy" to "а",
    "aelig" to "æ",
    "af" to "⁡",
    "afr" to "𝔞",
    "agrave" to "à",
    "alefsym" to "ℵ",
    "aleph" to "ℵ",
    "alpha" to "α",
    "amacr" to "ā",
    "amalg" to "⨿",
    "amp" to "&",
    "and" to "∧",
    "andand" to "⩕",
    "andd" to "⩜",
    "andslope" to "⩘",
    "andv" to "⩚",
    "ang" to "∠",
    "ange" to "⦤",
    "angle" to "∠",
    "angmsd" to "∡",
    "angmsdaa" to "⦨",
    "angmsdab" to "⦩",
    "angmsdac" to "⦪",
    "angmsdad" to "⦫",
    "angmsdae" to "⦬",
    "angmsdaf" to "⦭",
    "angmsdag" to "⦮",
    "angmsdah" to "⦯",
    "angrt" to "∟",
    "angrtvb" to "⊾",
    "angrtvbd" to "⦝",
    "angsph" to "∢",
    "angst" to "Å",
    "angzarr" to "⍼",
    "aogon" to "ą",
    "aopf" to "𝕒",
    "ap" to "≈",
    "apE" to "⩰",
    "apacir" to "⩯",
    "ape" to "≊",
    "apid" to "≋",
    "apos" to "'",
    "approx" to "≈",
    "approxeq" to "≊",
    "aring" to "å",
    "ascr" to "𝒶",
    "ast" to "*",
    "asymp" to "≈",
    "asympeq" to "≍",
    "atilde" to "ã",
    "auml" to "ä",
    "awconint" to "∳",
    "awint" to "⨑",
    "bNot" to "⫭",
    "backcong" to "≌",
    "backepsilon" to "϶",
    "backprime" to "‵",
    "backsim" to "∽",
    "backsimeq" to "⋍",
    "barvee" to "⊽",
    "barwed" to "⌅",
    "barwedge" to "⌅",
    "bbrk" to "⎵",
    "bbrktbrk" to "⎶",
    "bcong" to "≌",
    "bcy" to "б",
    "bdquo" to "„",
    "becaus" to "∵",
    "because" to "∵",
    "bemptyv" to "⦰",
    "bepsi" to "϶",
    "bernou" to "ℬ",
    "beta" to "β",
    "beth" to "ℶ",
    "between" to "≬",
    "bfr" to "𝔟",
    "bigcap" to "⋂",
    "bigcirc" to "◯",
    "bigcup" to "⋃",
    "bigodot" to "⨀",
    "bigoplus" to "⨁",
    "bigotimes" to "⨂",
    "bigsqcup" to "⨆",
    "bigstar" to "★",
    "bigtriangledown" to "▽",
    "bigtriangleup" to "△",
    "biguplus" to "⨄",
    "bigvee" to "⋁",
    "bigwedge" to "⋀",
    "bkarow" to "⤍",
    "blacklozenge" to "⧫",
    "blacksquare" to "▪",
    "blacktriangle" to "▴",
    "blacktriangledown" to "▾",
    "blacktriangleleft" to "◂",
    "blacktriangleright" to "▸",
    "blank" to "␣",
    "blk12" to "▒",
    "blk14" to "░",
    "blk34" to "▓",
    "block" to "█",
    "bne" to "=⃥",
    "bnequiv" to "≡⃥",
    "bnot" to "⌐",
    "bopf" to "𝕓",
    "bot" to "⊥",
    "bottom" to "⊥",
    "bowtie" to "⋈",
    "boxDL" to "╗",
    "boxDR" to "╔",
    "boxDl" to "╖",
    "boxDr" to "╓",
    "boxH" to "═",
    "boxHD" to "╦",
    "boxHU" to "╩",
    "boxHd" to "╤",
    "boxHu" to "╧",
    "boxUL" to "╝",
    "boxUR" to "╚",
    "boxUl" to "╜",
    "boxUr" to "╙",
    "boxV" to "║",
    "boxVH" to "╬",
    "boxVL" to "╣",
    "boxVR" to "╠",
    "boxVh" to "╫",
    "boxVl" to "╢",
    "boxVr" to "╟",
    "boxbox" to "⧉",
    "boxdL" to "╕",
    "boxdR" to "╒",
    "boxdl" to "┐",
    "boxdr" to "┌",
    "boxh" to "─",
    "boxhD" to "╥",
    "boxhU" to "╨",
    "boxhd" to "┬",
    "boxhu" to "┴",
    "boxminus" to "⊟",
    "boxplus" to "⊞",
    "boxtimes" to "⊠",
    "boxuL" to "╛",
    "boxuR" to "╘",
    "boxul" to "┘",
    "boxur" to "└",
    "boxv" to "│",
    "boxvH" to "╪",
    "boxvL" to "╡",
    "boxvR" to "╞",
    "boxvh" to "┼",
    "boxvl" to "┤",
    "boxvr" to "├",
    "bprime" to "‵",
    "breve" to "˘",
    "brvbar" to "¦",
    "bscr" to "𝒷",
    "bsemi" to "⁏",
    "bsim" to "∽",
    "bsime" to "⋍",
    "bsol" to "\u005C",
    "bsolb" to "⧅",
    "bsolhsub" to "⟈",
    "bull" to "•",
    "bullet" to "•",
    "bump" to "≎",
    "bumpE" to "⪮",
    "bumpe" to "≏",
    "bumpeq" to "≏",
    "cacute" to "ć",
    "cap" to "∩",
    "capand" to "⩄",
    "capbrcup" to "⩉",
    "capcap" to "⩋",
    "capcup" to "⩇",
    "capdot" to "⩀",
    "caps" to "∩︀",
    "caret" to "⁁",
    "caron" to "ˇ",
    "ccaps" to "⩍",
    "ccaron" to "č",
    "ccedil" to "ç",
    "ccirc" to "ĉ",
    "ccups" to "⩌",
    "ccupssm" to "⩐",
    "cdot" to "ċ",
    "cedil" to "¸",
    "cemptyv" to "⦲",
    "cent" to "¢",
    "centerdot" to "·",
    "cfr" to "𝔠",
    "chcy" to "ч",
    "check" to "✓",
    "checkmark" to "✓",
    "chi" to "χ",
    "cir" to "○",
    "cirE" to "⧃",
    "circ" to "ˆ",
    "circeq" to "≗",
    "circlearrowleft" to "↺",
    "circlearrowright" to "↻",
    "circledR" to "®",
    "circledS" to "Ⓢ",
    "circledast" to "⊛",
    "circledcirc" to "⊚",
    "circleddash" to "⊝",
    "cire" to "≗",
    "cirfnint" to "⨐",
    "cirmid" to "⫯",
    "cirscir" to "⧂",
    "clubs" to "♣",
    "clubsuit" to "♣",
    "colon" to ":",
    "colone" to "≔",
    "coloneq" to "≔",
    "comma" to ",",
    "commat" to "@",
    "comp" to "∁",
    "compfn" to "∘",
    "complement" to "∁",
    "complexes" to "ℂ",
    "cong" to "≅",
    "congdot" to "⩭",
    "conint" to "∮",
    "copf" to "𝕔",
    "coprod" to "∐",
    "copy" to "©",
    "copysr" to "℗",
    "crarr" to "↵",
    "cross" to "✗",
    "cscr" to "𝒸",
    "csub" to "⫏",
    "csube" to "⫑",
    "csup" to "⫐",
    "csupe" to "⫒",
    "ctdot" to "⋯",
    "cudarrl" to "⤸",
    "cudarrr" to "⤵",
    "cuepr" to "⋞",
    "cuesc" to "⋟",
    "cularr" to "↶",
    "cularrp" to "⤽",
    "cup" to "∪",
    "cupbrcap" to "⩈",
    "cupcap" to "⩆",
    "cupcup" to "⩊",
    "cupdot" to "⊍",
    "cupor" to "⩅",
    "cups" to "∪︀",
    "curarr" to "↷",
    "curarrm" to "⤼",
    "curlyeqprec" to "⋞",
    "curlyeqsucc" to "⋟",
    "curlyvee" to "⋎",
    "curlywedge" to "⋏",
    "curren" to "¤",
    "curvearrowleft" to "↶",
    "curvearrowright" to "↷",
    "cuvee" to "⋎",
    "cuwed" to "⋏",
    "cwconint" to "∲",
    "cwint" to "∱",
    "cylcty" to "⌭",
    "dArr" to "⇓",
    "dHar" to "⥥",
    "dagger" to "†",
    "daleth" to "ℸ",
    "darr" to "↓",
    "dash" to "‐",
    "dashv" to "⊣",
    "dbkarow" to "⤏",
    "dblac" to "˝",
    "dcaron" to "ď",
    "dcy" to "д",
    "dd" to "ⅆ",
    "ddagger" to "‡",
    "ddarr" to "⇊",
    "ddotseq" to "⩷",
    "deg" to "°",
    "delta" to "δ",
    "demptyv" to "⦱",
    "dfisht" to "⥿",
    "dfr" to "𝔡",
    "dharl" to "⇃",
    "dharr" to "⇂",
    "diam" to "⋄",
    "diamond" to "⋄",
    "diamondsuit" to "♦",
    "diams" to "♦",
    "die" to "¨",
    "digamma" to "ϝ",
    "disin" to "⋲",
    "div" to "÷",
    "divide" to "÷",
    "divideontimes" to "⋇",
    "divonx" to "⋇",
    "djcy" to "ђ",
    "dlcorn" to "⌞",
    "dlcrop" to "⌍",
    "dollar" to "$",
    "dopf" to "𝕕",
    "dot" to "˙",
    "doteq" to "≐",
    "doteqdot" to "≑",
    "dotminus" to "∸",
    "dotplus" to "∔",
    "dotsquare" to "⊡",
    "doublebarwedge" to "⌆",
    "downarrow" to "↓",
    "downdownarrows" to "⇊",
    "downharpoonleft" to "⇃",
    "downharpoonright" to "⇂",
    "drbkarow" to "⤐",
    "drcorn" to "⌟",
    "drcrop" to "⌌",
    "dscr" to "𝒹",
    "dscy" to "ѕ",
    "dsol" to "⧶",
    "dstrok" to "đ",
    "dtdot" to "⋱",
    "dtri" to "▿",
    "dtrif" to "▾",
    "duarr" to "⇵",
    "duhar" to "⥯",
    "dwangle" to "⦦",
    "dzcy" to "џ",
    "dzigrarr" to "⟿",
    "eDDot" to "⩷",
    "eDot" to "≑",
    "eacute" to "é",
    "easter" to "⩮",
    "ecaron" to "ě",
    "ecir" to "≖",
    "ecirc" to "ê",
    "ecolon" to "≕",
    "ecy" to "э",
    "edot" to "ė",
    "ee" to "ⅇ",
    "efDot" to "≒",
    "efr" to "𝔢",
    "eg" to "⪚",
    "egrave" to "è",
    "egs" to "⪖",
    "egsdot" to "⪘",
    "el" to "⪙",
    "elinters" to "⏧",
    "ell" to "ℓ",
    "els" to "⪕",
    "elsdot" to "⪗",
    "emacr" to "ē",
    "empty" to "∅",
    "emptyset" to "∅",
    "emptyv" to "∅",
    "emsp" to " ",
    "emsp13" to " ",
    "emsp14" to " ",
    "eng" to "ŋ",
    "ensp" to " ",
    "eogon" to "ę",
    "eopf" to "𝕖",
    "epar" to "⋕",
    "eparsl" to "⧣",
    "eplus" to "⩱",
    "epsi" to "ε",
    "epsilon" to "ε",
    "epsiv" to "ϵ",
    "eqcirc" to "≖",
    "eqcolon" to "≕",
    "eqsim" to "≂",
    "eqslantgtr" to "⪖",
    "eqslantless" to "⪕",
    "equals" to "=",
    "equest" to "≟",
    "equiv" to "≡",
    "equivDD" to "⩸",
    "eqvparsl" to "⧥",
    "erDot" to "≓",
    "erarr" to "⥱",
    "escr" to "ℯ",
    "esdot" to "≐",
    "esim" to "≂",
    "eta" to "η",
    "eth" to "ð",
    "euml" to "ë",
    "euro" to "€",
    "excl" to "!",
    "exist" to "∃",
    "expectation" to "ℰ",
    "exponentiale" to "ⅇ",
    "fallingdotseq" to "≒",
    "fcy" to "ф",
    "female" to "♀",
    "ffilig" to "ﬃ",
    "fflig" to "ﬀ",
    "ffllig" to "ﬄ",
    "ffr" to "𝔣",
    "filig" to "ﬁ",
    "fjlig" to "fj",
    "flat" to "♭",
    "fllig" to "ﬂ",
    "fltns" to "▱",
    "fnof" to "ƒ",
    "fopf" to "𝕗",
    "forall" to "∀",
    "fork" to "⋔",
    "forkv" to "⫙",
    "fpartint" to "⨍",
    "frac12" to "½",
    "frac13" to "⅓",
    "frac14" to "¼",
    "frac15" to "⅕",
    "frac16" to "⅙",
    "frac18" to "⅛",
    "frac23" to "⅔",
    "frac25" to "⅖",
    "frac34" to "¾",
    "frac35" to "⅗",
    "frac38" to "⅜",
    "frac45" to "⅘",
    "frac56" to "⅚",
    "frac58" to "⅝",
    "frac78" to "⅞",
    "frasl" to "⁄",
    "frown" to "⌢",
    "fscr" to "𝒻",
    "gE" to "≧",
    "gEl" to "⪌",
    "gacute" to "ǵ",
    "gamma" to "γ",
    "gammad" to "ϝ",
    "gap" to "⪆",
    "gbreve" to "ğ",
    "gcirc" to "ĝ",
    "gcy" to "г",
    "gdot" to "ġ",
    "ge" to "≥",
    "gel" to "⋛",
    "geq" to "≥",
    "geqq" to "≧",
    "geqslant" to "⩾",
    "ges" to "⩾",
    "gescc" to "⪩",
    "gesdot" to "⪀",
    "gesdoto" to "⪂",
    "gesdotol" to "⪄",
    "gesl" to "⋛︀",
    "gesles" to "⪔",
    "gfr" to "𝔤",
    "gg" to "≫",
    "ggg" to "⋙",
    "gimel" to "ℷ",
    "gjcy" to "ѓ",
    "gl" to "≷",
    "glE" to "⪒",
    "gla" to "⪥",
    "glj" to "⪤",
    "gnE" to "≩",
    "gnap" to "⪊",
    "gnapprox" to "⪊",
    "gne" to "⪈",
    "gneq" to "⪈",
    "gneqq" to "≩",
    "gnsim" to "⋧",
    "gopf" to "𝕘",
    "grave" to "`",
    "gscr" to "ℊ",
    "gsim" to "≳",
    "gsime" to "⪎",
    "gsiml" to "⪐",
    "gt" to ">",
    "gtcc" to "⪧",
    "gtcir" to "⩺",
    "gtdot" to "⋗",
    "gtlPar" to "⦕",
    "gtquest" to "⩼",
    "gtrapprox" to "⪆",
    "gtrarr" to "⥸",
    "gtrdot" to "⋗",
    "gtreqless" to "⋛",
    "gtreqqless" to "⪌",
    "gtrless" to "≷",
    "gtrsim" to "≳",
    "gvertneqq" to "≩︀",
    "gvnE" to "≩︀",
    "hArr" to "⇔",
    "hairsp" to " ",
    "half" to "½",
    "hamilt" to "ℋ",
    "hardcy" to "ъ",
    "harr" to "↔",
    "harrcir" to "⥈",
    "harrw" to "↭",
    "hbar" to "ℏ",
    "hcirc" to "ĥ",
    "hearts" to "♥",
    "heartsuit" to "♥",
    "hellip" to "…",
    "hercon" to "⊹",
    "hfr" to "𝔥",
    "hksearow" to "⤥",
    "hkswarow" to "⤦",
    "hoarr" to "⇿",
    "homtht" to "∻",
    "hookleftarrow" to "↩",
    "hookrightarrow" to "↪",
    "hopf" to "𝕙",
    "horbar" to "―",
    "hscr" to "𝒽",
    "hslash" to "ℏ",
    "hstrok" to "ħ",
    "hybull" to "⁃",
    "hyphen" to "‐",
    "iacute" to "í",
    "ic" to "⁣",
    "icirc" to "î",
    "icy" to "и",
    "iecy" to "е",
    "iexcl" to "¡",
    "iff" to "⇔",
    "ifr" to "𝔦",
    "igrave" to "ì",
    "ii" to "ⅈ",
    "iiiint" to "⨌",
    "iiint" to "∭",
    "iinfin" to "⧜",
    "iiota" to "℩",
    "ijlig" to "ĳ",
    "imacr" to "ī",
    "image" to "ℑ",
    "imagline" to "ℐ",
    "imagpart" to "ℑ",
    "imath" to "ı",
    "imof" to "⊷",
    "imped" to "Ƶ",
    "in" to "∈",
    "incare" to "℅",
    "infin" to "∞",
    "infintie" to "⧝",
    "inodot" to "ı",
    "int" to "∫",
    "intcal" to "⊺",
    "integers" to "ℤ",
    "intercal" to "⊺",
    "intlarhk" to "⨗",
    "intprod" to "⨼",
    "iocy" to "ё",
    "iogon" to "į",
    "iopf" to "𝕚",
    "iota" to "ι",
    "iprod" to "⨼",
    "iquest" to "¿",
    "iscr" to "𝒾",
    "isin" to "∈",
    "isinE" to "⋹",
    "isindot" to "⋵",
    "isins" to "⋴",
    "isinsv" to "⋳",
    "isinv" to "∈",
    "it" to "⁢",
    "itilde" to "ĩ",
    "iukcy" to "і",
    "iuml" to "ï",
    "jcirc" to "ĵ",
    "jcy" to "й",
    "jfr" to "𝔧",
    "jmath" to "ȷ",
    "jopf" to "𝕛",
    "jscr" to "𝒿",
    "jsercy" to "ј",
    "jukcy" to "є",
    "kappa" to "κ",
    "kappav" to "ϰ",
    "kcedil" to "ķ",
    "kcy" to "к",
    "kfr" to "𝔨",
    "kgreen" to "ĸ",
    "khcy" to "х",
    "kjcy" to "ќ",
    "kopf" to "𝕜",
    "kscr" to "𝓀",
    "lAarr" to "⇚",
    "lArr" to "⇐",
    "lAtail" to "⤛",
    "lBarr" to "⤎",
    "lE" to "≦",
    "lEg" to "⪋",
    "lHar" to "⥢",
    "lacute" to "ĺ",
    "laemptyv" to "⦴",
    "lagran" to "ℒ",
    "lambda" to "λ",
    "lang" to "〈",
    "langd" to "⦑",
    "langle" to "〈",
    "lap" to "⪅",
    "laquo" to "«",
    "larr" to "←",
    "larrb" to "⇤",
    "larrbfs" to "⤟",
    "larrfs" to "⤝",
    "larrhk" to "↩",
    "larrlp" to "↫",
    "larrpl" to "⤹",
    "larrsim" to "⥳",
    "larrtl" to "↢",
    "lat" to "⪫",
    "latail" to "⤙",
    "late" to "⪭",
    "lates" to "⪭︀",
    "lbarr" to "⤌",
    "lbbrk" to "❲",
    "lbrace" to "{",
    "lbrack" to "[",
    "lbrke" to "⦋",
    "lbrksld" to "⦏",
    "lbrkslu" to "⦍",
    "lcaron" to "ľ",
    "lcedil" to "ļ",
    "lceil" to "⌈",
    "lcub" to "{",
    "lcy" to "л",
    "ldca" to "⤶",
    "ldquo" to "“",
    "ldquor" to "„",
    "ldrdhar" to "⥧",
    "ldrushar" to "⥋",
    "ldsh" to "↲",
    "le" to "≤",
    "leftarrow" to "←",
    "leftarrowtail" to "↢",
    "leftharpoondown" to "↽",
    "leftharpoonup" to "↼",
    "leftleftarrows" to "⇇",
    "leftrightarrow" to "↔",
    "leftrightarrows" to "⇆",
    "leftrightharpoons" to "⇋",
    "leftrightsquigarrow" to "↭",
    "leftthreetimes" to "⋋",
    "leg" to "⋚",
    "leq" to "≤",
    "leqq" to "≦",
    "leqslant" to "⩽",
    "les" to "⩽",
    "lescc" to "⪨",
    "lesdot" to "⩿",
    "lesdoto" to "⪁",
    "lesdotor" to "⪃",
    "lesg" to "⋚︀",
    "lesges" to "⪓",
    "lessapprox" to "⪅",
    "lessdot" to "⋖",
    "lesseqgtr" to "⋚",
    "lesseqqgtr" to "⪋",
    "lessgtr" to "≶",
    "lesssim" to "≲",
    "lfisht" to "⥼",
    "lfloor" to "⌊",
    "lfr" to "𝔩",
    "lg" to "≶",
    "lgE" to "⪑",
    "lhard" to "↽",
    "lharu" to "↼",
    "lharul" to "⥪",
    "lhblk" to "▄",
    "ljcy" to "љ",
    "ll" to "≪",
    "llarr" to "⇇",
    "llcorner" to "⌞",
    "llhard" to "⥫",
    "lltri" to "◺",
    "lmidot" to "ŀ",
    "lmoust" to "⎰",
    "lmoustache" to "⎰",
    "lnE" to "≨",
    "lnap" to "⪉",
    "lnapprox" to "⪉",
    "lne" to "⪇",
    "lneq" to "⪇",
    "lneqq" to "≨",
    "lnsim" to "⋦",
    "loang" to "⟬",
    "loarr" to "⇽",
    "lobrk" to "⟦",
    "longleftarrow" to "⟵",
    "longleftrightarrow" to "⟷",
    "longmapsto" to "⟼",
    "longrightarrow" to "⟶",
    "looparrowleft" to "↫",
    "looparrowright" to "↬",
    "lopar" to "⦅",
    "lopf" to "𝕝",
    "loplus" to "⨭",
    "lotimes" to "⨴",
    "lowast" to "∗",
    "lowbar" to "_",
    "loz" to "◊",
    "lozenge" to "◊",
    "lozf" to "⧫",
    "lpar" to "(",
    "lparlt" to "⦓",
    "lrarr" to "⇆",
    "lrcorner" to "⌟",
    "lrhar" to "⇋",
    "lrhard" to "⥭",
    "lrm" to "‎",
    "lrtri" to "⊿",
    "lsaquo" to "‹",
    "lscr" to "𝓁",
    "lsh" to "↰",
    "lsim" to "≲",
    "lsime" to "⪍",
    "lsimg" to "⪏",
    "lsqb" to "[",
    "lsquo" to "‘",
    "lsquor" to "‚",
    "lstrok" to "ł",
    "lt" to "<",
    "ltcc" to "⪦",
    "ltcir" to "⩹",
    "ltdot" to "⋖",
    "lthree" to "⋋",
    "ltimes" to "⋉",
    "ltlarr" to "⥶",
    "ltquest" to "⩻",
    "ltrPar" to "⦖",
    "ltri" to "◃",
    "ltrie" to "⊴",
    "ltrif" to "◂",
    "lurdshar" to "⥊",
    "luruhar" to "⥦",
    "lvertneqq" to "≨︀",
    "lvnE" to "≨︀",
    "mDDot" to "∺",
    "macr" to "¯",
    "male" to "♂",
    "malt" to "✠",
    "maltese" to "✠",
    "map" to "↦",
    "mapsto" to "↦",
    "mapstodown" to "↧",
    "mapstoleft" to "↤",
    "mapstoup" to "↥",
    "marker" to "▮",
    "mcomma" to "⨩",
    "mcy" to "м",
    "mdash" to "—",
    "measuredangle" to "∡",
    "mfr" to "𝔪",
    "mho" to "℧",
    "micro" to "µ",
    "mid" to "∣",
    "midast" to "*",
    "midcir" to "⫰",
    "middot" to "·",
    "minus" to "−",
    "minusb" to "⊟",
    "minusd" to "∸",
    "minusdu" to "⨪",
    "mlcp" to "⫛",
    "mldr" to "…",
    "mnplus" to "∓",
    "models" to "⊧",
    "mopf" to "𝕞",
    "mp" to "∓",
    "mscr" to "𝓂",
    "mstpos" to "∾",
    "mu" to "μ",
    "multimap" to "⊸",
    "mumap" to "⊸",
    "nGg" to "⋙̸",
    "nGt" to "≫⃒",
    "nGtv" to "≫̸",
    "nLeftarrow" to "⇍",
    "nLeftrightarrow" to "⇎",
    "nLl" to "⋘̸",
    "nLt" to "≪⃒",
    "nLtv" to "≪̸",
    "nRightarrow" to "⇏",
    "nVDash" to "⊯",
    "nVdash" to "⊮",
    "nabla" to "∇",
    "nacute" to "ń",
    "nang" to "∠⃒",
    "nap" to "≉",
    "napE" to "⩰̸",
    "napid" to "≋̸",
    "napos" to "ŉ",
    "napprox" to "≉",
    "natur" to "♮",
    "natural" to "♮",
    "naturals" to "ℕ",
    "nbsp" to "\u00A0",
    "nbump" to "≎̸",
    "nbumpe" to "≏̸",
    "ncap" to "⩃",
    "ncaron" to "ň",
    "ncedil" to "ņ",
    "ncong" to "≇",
    "ncongdot" to "⩭̸",
    "ncup" to "⩂",
    "ncy" to "н",
    "ndash" to "–",
    "ne" to "≠",
    "neArr" to "⇗",
    "nearhk" to "⤤",
    "nearr" to "↗",
    "nearrow" to "↗",
    "nedot" to "≐̸",
    "nequiv" to "≢",
    "nesear" to "⤨",
    "nesim" to "≂̸",
    "nexist" to "∄",
    "nexists" to "∄",
    "nfr" to "𝔫",
    "ngE" to "≧̸",
    "nge" to "≱",
    "ngeq" to "≱",
    "ngeqq" to "≧̸",
    "ngeqslant" to "⩾̸",
    "nges" to "⩾̸",
    "ngsim" to "≵",
    "ngt" to "≯",
    "ngtr" to "≯",
    "nhArr" to "⇎",
    "nharr" to "↮",
    "nhpar" to "⫲",
    "ni" to "∋",
    "nis" to "⋼",
    "nisd" to "⋺",
    "niv" to "∋",
    "njcy" to "њ",
    "nlArr" to "⇍",
    "nlE" to "≦̸",
    "nlarr" to "↚",
    "nldr" to "‥",
    "nle" to "≰",
    "nleftarrow" to "↚",
    "nleftrightarrow" to "↮",
    "nleq" to "≰",
    "nleqq" to "≦̸",
    "nleqslant" to "⩽̸",
    "nles" to "⩽̸",
    "nless" to "≮",
    "nlsim" to "≴",
    "nlt" to "≮",
    "nltri" to "⋪",
    "nltrie" to "⋬",
    "nmid" to "∤",
    "nopf" to "𝕟",
    "not" to "¬",
    "notin" to "∉",
    "notinE" to "⋹̸",
    "notindot" to "⋵̸",
    "notinva" to "∉",
    "notinvb" to "⋷",
    "notinvc" to "⋶",
    "notni" to "∌",
    "notniva" to "∌",
    "notnivb" to "⋾",
    "notnivc" to "⋽",
    "npar" to "∦",
    "nparallel" to "∦",
    "nparsl" to "⫽⃥",
    "npart" to "∂̸",
    "npolint" to "⨔",
    "npr" to "⊀",
    "nprcue" to "⋠",
    "npre" to "⪯̸",
    "nprec" to "⊀",
    "npreceq" to "⪯̸",
    "nrArr" to "⇏",
    "nrarr" to "↛",
    "nrarrc" to "⤳̸",
    "nrarrw" to "↝̸",
    "nrightarrow" to "↛",
    "nrtri" to "⋫",
    "nrtrie" to "⋭",
    "nsc" to "⊁",
    "nsccue" to "⋡",
    "nsce" to "⪰̸",
    "nscr" to "𝓃",
    "nshortmid" to "∤",
    "nshortparallel" to "∦",
    "nsim" to "≁",
    "nsime" to "≄",
    "nsimeq" to "≄",
    "nsmid" to "∤",
    "nspar" to "∦",
    "nsqsube" to "⋢",
    "nsqsupe" to "⋣",
    "nsub" to "⊄",
    "nsubE" to "⫅̸",
    "nsube" to "⊈",
    "nsubset" to "⊂⃒",
    "nsubseteq" to "⊈",
    "nsubseteqq" to "⫅̸",
    "nsucc" to "⊁",
    "nsucceq" to "⪰̸",
    "nsup" to "⊅",
    "nsupE" to "⫆̸",
    "nsupe" to "⊉",
    "nsupset" to "⊃⃒",
    "nsupseteq" to "⊉",
    "nsupseteqq" to "⫆̸",
    "ntgl" to "≹",
    "ntilde" to "ñ",
    "ntlg" to "≸",
    "ntriangleleft" to "⋪",
    "ntrianglelefteq" to "⋬",
    "ntriangleright" to "⋫",
    "ntrianglerighteq" to "⋭",
    "nu" to "ν",
    "num" to "#",
    "numero" to "№",
    "numsp" to " ",
    "nvDash" to "⊭",
    "nvHarr" to "⤄",
    "nvap" to "≍⃒",
    "nvdash" to "⊬",
    "nvge" to "≥⃒",
    "nvgt" to ">⃒",
    "nvinfin" to "⧞",
    "nvlArr" to "⤂",
    "nvle" to "≤⃒",
    "nvlt" to "<⃒",
    "nvltrie" to "⊴⃒",
    "nvrArr" to "⤃",
    "nvrtrie" to "⊵⃒",
    "nvsim" to "∼⃒",
    "nwArr" to "⇖",
    "nwarhk" to "⤣",
    "nwarr" to "↖",
    "nwarrow" to "↖",
    "nwnear" to "⤧",
    "oS" to "Ⓢ",
    "oacute" to "ó",
    "oast" to "⊛",
    "ocir" to "⊚",
    "ocirc" to "ô",
    "ocy" to "о",
    "odash" to "⊝",
    "odblac" to "ő",
    "odiv" to "⨸",
    "odot" to "⊙",
    "odsold" to "⦼",
    "oelig" to "œ",
    "ofcir" to "⦿",
    "ofr" to "𝔬",
    "ogon" to "˛",
    "ograve" to "ò",
    "ogt" to "⧁",
    "ohbar" to "⦵",
    "ohm" to "Ω",
    "oint" to "∮",
    "olarr" to "↺",
    "olcir" to "⦾",
    "olcross" to "⦻",
    "oline" to "‾",
    "olt" to "⧀",
    "omacr" to "ō",
    "omega" to "ω",
    "omicron" to "ο",
    "omid" to "⦶",
    "ominus" to "⊖",
    "oopf" to "𝕠",
    "opar" to "⦷",
    "operp" to "⦹",
    "oplus" to "⊕",
    "or" to "∨",
    "orarr" to "↻",
    "ord" to "⩝",
    "order" to "ℴ",
    "orderof" to "ℴ",
    "ordf" to "ª",
    "ordm" to "º",
    "origof" to "⊶",
    "oror" to "⩖",
    "orslope" to "⩗",
    "orv" to "⩛",
    "oscr" to "ℴ",
    "oslash" to "ø",
    "osol" to "⊘",
    "otilde" to "õ",
    "otimes" to "⊗",
    "otimesas" to "⨶",
    "ouml" to "ö",
    "ovbar" to "⌽",
    "par" to "∥",
    "para" to "¶",
    "parallel" to "∥",
    "parsim" to "⫳",
    "parsl" to "⫽",
    "part" to "∂",
    "pcy" to "п",
    "percnt" to "%",
    "period" to ".",
    "permil" to "‰",
    "perp" to "⊥",
    "pertenk" to "‱",
    "pfr" to "𝔭",
    "phi" to "φ",
    "phiv" to "ϕ",
    "phmmat" to "ℳ",
    "phone" to "☎",
    "pi" to "π",
    "pitchfork" to "⋔",
    "piv" to "ϖ",
    "planck" to "ℏ",
    "planckh" to "ℎ",
    "plankv" to "ℏ",
    "plus" to "+",
    "plusacir" to "⨣",
    "plusb" to "⊞",
    "pluscir" to "⨢",
    "plusdo" to "∔",
    "plusdu" to "⨥",
    "pluse" to "⩲",
    "plusmn" to "±",
    "plussim" to "⨦",
    "plustwo" to "⨧",
    "pm" to "±",
    "pointint" to "⨕",
    "popf" to "𝕡",
    "pound" to "£",
    "pr" to "≺",
    "prE" to "⪳",
    "prap" to "⪷",
    "prcue" to "≼",
    "pre" to "⪯",
    "prec" to "≺",
    "precapprox" to "⪷",
    "preccurlyeq" to "≼",
    "preceq" to "⪯",
    "precnapprox" to "⪹",
    "precneqq" to "⪵",
    "precnsim" to "⋨",
    "precsim" to "≾",
    "prime" to "′",
    "primes" to "ℙ",
    "prnE" to "⪵",
    "prnap" to "⪹",
    "prnsim" to "⋨",
    "prod" to "∏",
    "profalar" to "⌮",
    "profline" to "⌒",
    "profsurf" to "⌓",
    "prop" to "∝",
    "propto" to "∝",
    "prsim" to "≾",
    "prurel" to "⊰",
    "pscr" to "𝓅",
    "psi" to "ψ",
    "puncsp" to " ",
    "qfr" to "𝔮",
    "qint" to "⨌",
    "qopf" to "𝕢",
    "qprime" to "⁗",
    "qscr" to "𝓆",
    "quaternions" to "ℍ",
    "quatint" to "⨖",
    "quest" to "?",
    "questeq" to "≟",
    "quot" to "\"",
    "rAarr" to "⇛",
    "rArr" to "⇒",
    "rAtail" to "⤜",
    "rBarr" to "⤏",
    "rHar" to "⥤",
    "race" to "∽̱",
    "racute" to "ŕ",
    "radic" to "√",
    "raemptyv" to "⦳",
    "rang" to "〉",
    "rangd" to "⦒",
    "range" to "⦥",
    "rangle" to "〉",
    "raquo" to "»",
    "rarr" to "→",
    "rarrap" to "⥵",
    "rarrb" to "⇥",
    "rarrbfs" to "⤠",
    "rarrc" to "⤳",
    "rarrfs" to "⤞",
    "rarrhk" to "↪",
    "rarrlp" to "↬",
    "rarrpl" to "⥅",
    "rarrsim" to "⥴",
    "rarrtl" to "↣",
    "rarrw" to "↝",
    "ratail" to "⤚",
    "ratio" to "∶",
    "rationals" to "ℚ",
    "rbarr" to "⤍",
    "rbbrk" to "❳",
    "rbrace" to "}",
    "rbrack" to "]",
    "rbrke" to "⦌",
    "rbrksld" to "⦎",
    "rbrkslu" to "⦐",
    "rcaron" to "ř",
    "rcedil" to "ŗ",
    "rceil" to "⌉",
    "rcub" to "}",
    "rcy" to "р",
    "rdca" to "⤷",
    "rdldhar" to "⥩",
    "rdquo" to "”",
    "rdquor" to "”",
    "rdsh" to "↳",
    "real" to "ℜ",
    "realine" to "ℛ",
    "realpart" to "ℜ",
    "reals" to "ℝ",
    "rect" to "▭",
    "reg" to "®",
    "rfisht" to "⥽",
    "rfloor" to "⌋",
    "rfr" to "𝔯",
    "rhard" to "⇁",
    "rharu" to "⇀",
    "rharul" to "⥬",
    "rho" to "ρ",
    "rhov" to "ϱ",
    "rightarrow" to "→",
    "rightarrowtail" to "↣",
    "rightharpoondown" to "⇁",
    "rightharpoonup" to "⇀",
    "rightleftarrows" to "⇄",
    "rightleftharpoons" to "⇌",
    "rightrightarrows" to "⇉",
    "rightsquigarrow" to "↝",
    "rightthreetimes" to "⋌",
    "ring" to "˚",
    "risingdotseq" to "≓",
    "rlarr" to "⇄",
    "rlhar" to "⇌",
    "rlm" to "‏",
    "rmoust" to "⎱",
    "rmoustache" to "⎱",
    "rnmid" to "⫮",
    "roang" to "⟭",
    "roarr" to "⇾",
    "robrk" to "⟧",
    "ropar" to "⦆",
    "ropf" to "𝕣",
    "roplus" to "⨮",
    "rotimes" to "⨵",
    "rpar" to ")",
    "rpargt" to "⦔",
    "rppolint" to "⨒",
    "rrarr" to "⇉",
    "rsaquo" to "›",
    "rscr" to "𝓇",
    "rsh" to "↱",
    "rsqb" to "]",
    "rsquo" to "’",
    "rsquor" to "’",
    "rthree" to "⋌",
    "rtimes" to "⋊",
    "rtri" to "▹",
    "rtrie" to "⊵",
    "rtrif" to "▸",
    "rtriltri" to "⧎",
    "ruluhar" to "⥨",
    "rx" to "℞",
    "sacute" to "ś",
    "sbquo" to "‚",
    "sc" to "≻",
    "scE" to "⪴",
    "scap" to "⪸",
    "scaron" to "š",
    "sccue" to "≽",
    "sce" to "⪰",
    "scedil" to "ş",
    "scirc" to "ŝ",
    "scnE" to "⪶",
    "scnap" to "⪺",
    "scnsim" to "⋩",
    "scpolint" to "⨓",
    "scsim" to "≿",
    "scy" to "с",
    "sdot" to "⋅",
    "sdotb" to "⊡",
    "sdote" to "⩦",
    "seArr" to "⇘",
    "searhk" to "⤥",
    "searr" to "↘",
    "searrow" to "↘",
    "sect" to "§",
    "semi" to ";",
    "seswar" to "⤩",
    "setminus" to "∖",
    "setmn" to "∖",
    "sext" to "✶",
    "sfr" to "𝔰",
    "sfrown" to "⌢",
    "sharp" to "♯",
    "shchcy" to "щ",
    "shcy" to "ш",
    "shortmid" to "∣",
    "shortparallel" to "∥",
    "shy" to "­",
    "sigma" to "σ",
    "sigmaf" to "ς",
    "sigmav" to "ς",
    "sim" to "∼",
    "simdot" to "⩪",
    "sime" to "≃",
    "simeq" to "≃",
    "simg" to "⪞",
    "simgE" to "⪠",
    "siml" to "⪝",
    "simlE" to "⪟",
    "simne" to "≆",
    "simplus" to "⨤",
    "simrarr" to "⥲",
    "slarr" to "←",
    "smallsetminus" to "∖",
    "smashp" to "⨳",
    "smeparsl" to "⧤",
    "smid" to "∣",
    "smile" to "⌣",
    "smt" to "⪪",
    "smte" to "⪬",
    "smtes" to "⪬︀",
    "softcy" to "ь",
    "sol" to "/",
    "solb" to "⧄",
    "solbar" to "⌿",
    "sopf" to "𝕤",
    "spades" to "♠",
    "spadesuit" to "♠",
    "spar" to "∥",
    "sqcap" to "⊓",
    "sqcaps" to "⊓︀",
    "sqcup" to "⊔",
    "sqcups" to "⊔︀",
    "sqsub" to "⊏",
    "sqsube" to "⊑",
    "sqsubset" to "⊏",
    "sqsubseteq" to "⊑",
    "sqsup" to "⊐",
    "sqsupe" to "⊒",
    "sqsupset" to "⊐",
    "sqsupseteq" to "⊒",
    "squ" to "□",
    "square" to "□",
    "squarf" to "▪",
    "squf" to "▪",
    "srarr" to "→",
    "sscr" to "𝓈",
    "ssetmn" to "∖",
    "ssmile" to "⌣",
    "sstarf" to "⋆",
    "star" to "☆",
    "starf" to "★",
    "straightepsilon" to "ϵ",
    "straightphi" to "ϕ",
    "strns" to "¯",
    "sub" to "⊂",
    "subE" to "⫅",
    "subdot" to "⪽",
    "sube" to "⊆",
    "subedot" to "⫃",
    "submult" to "⫁",
    "subnE" to "⫋",
    "subne" to "⊊",
    "subplus" to "⪿",
    "subrarr" to "⥹",
    "subset" to "⊂",
    "subseteq" to "⊆",
    "subseteqq" to "⫅",
    "subsetneq" to "⊊",
    "subsetneqq" to "⫋",
    "subsim" to "⫇",
    "subsub" to "⫕",
    "subsup" to "⫓",
    "succ" to "≻",
    "succapprox" to "⪸",
    "succcurlyeq" to "≽",
    "succeq" to "⪰",
    "succnapprox" to "⪺",
    "succneqq" to "⪶",
    "succnsim" to "⋩",
    "succsim" to "≿",
    "sum" to "∑",
    "sung" to "♪",
    "sup" to "⊃",
    "sup1" to "¹",
    "sup2" to "²",
    "sup3" to "³",
    "supE" to "⫆",
    "supdot" to "⪾",
    "supdsub" to "⫘",
    "supe" to "⊇",
    "supedot" to "⫄",
    "suphsol" to "⟉",
    "suphsub" to "⫗",
    "suplarr" to "⥻",
    "supmult" to "⫂",
    "supnE" to "⫌",
    "supne" to "⊋",
    "supplus" to "⫀",
    "supset" to "⊃",
    "supseteq" to "⊇",
    "supseteqq" to "⫆",
    "supsetneq" to "⊋",
    "supsetneqq" to "⫌",
    "supsim" to "⫈",
    "supsub" to "⫔",
    "supsup" to "⫖",
    "swArr" to "⇙",
    "swarhk" to "⤦",
    "swarr" to "↙",
    "swarrow" to "↙",
    "swnwar" to "⤪",
    "szlig" to "ß",
    "target" to "⌖",
    "tau" to "τ",
    "tbrk" to "⎴",
    "tcaron" to "ť",
    "tcedil" to "ţ",
    "tcy" to "т",
    "tdot" to "\u20DB",
    "telrec" to "⌕",
    "tfr" to "𝔱",
    "there4" to "∴",
    "therefore" to "∴",
    "theta" to "θ",
    "thetasym" to "ϑ",
    "thetav" to "ϑ",
    "thickapprox" to "≈",
    "thicksim" to "∼",
    "thinsp" to " ",
    "thkap" to "≈",
    "thksim" to "∼",
    "thorn" to "þ",
    "tilde" to "˜",
    "times" to "×",
    "timesb" to "⊠",
    "timesbar" to "⨱",
    "timesd" to "⨰",
    "tint" to "∭",
    "toea" to "⤨",
    "top" to "⊤",
    "topbot" to "⌶",
    "topcir" to "⫱",
    "topf" to "𝕥",
    "topfork" to "⫚",
    "tosa" to "⤩",
    "tprime" to "‴",
    "trade" to "™",
    "triangle" to "▵",
    "triangledown" to "▿",
    "triangleleft" to "◃",
    "trianglelefteq" to "⊴",
    "triangleq" to "≜",
    "triangleright" to "▹",
    "trianglerighteq" to "⊵",
    "tridot" to "◬",
    "trie" to "≜",
    "triminus" to "⨺",
    "triplus" to "⨹",
    "trisb" to "⧍",
    "tritime" to "⨻",
    "trpezium" to "⏢",
    "tscr" to "𝓉",
    "tscy" to "ц",
    "tshcy" to "ћ",
    "tstrok" to "ŧ",
    "twixt" to "≬",
    "twoheadleftarrow" to "↞",
    "twoheadrightarrow" to "↠",
    "uArr" to "⇑",
    "uHar" to "⥣",
    "uacute" to "ú",
    "uarr" to "↑",
    "ubrcy" to "ў",
    "ubreve" to "ŭ",
    "ucirc" to "û",
    "ucy" to "у",
    "udarr" to "⇅",
    "udblac" to "ű",
    "udhar" to "⥮",
    "ufisht" to "⥾",
    "ufr" to "𝔲",
    "ugrave" to "ù",
    "uharl" to "↿",
    "uharr" to "↾",
    "uhblk" to "▀",
    "ulcorn" to "⌜",
    "ulcorner" to "⌜",
    "ulcrop" to "⌏",
    "ultri" to "◸",
    "umacr" to "ū",
    "uml" to "¨",
    "uogon" to "ų",
    "uopf" to "𝕦",
    "uparrow" to "↑",
    "updownarrow" to "↕",
    "upharpoonleft" to "↿",
    "upharpoonright" to "↾",
    "uplus" to "⊎",
    "upsi" to "υ",
    "upsih" to "ϒ",
    "upsilon" to "υ",
    "upuparrows" to "⇈",
    "urcorn" to "⌝",
    "urcorner" to "⌝",
    "urcrop" to "⌎",
    "uring" to "ů",
    "urtri" to "◹",
    "uscr" to "𝓊",
    "utdot" to "⋰",
    "utilde" to "ũ",
    "utri" to "▵",
    "utrif" to "▴",
    "uuarr" to "⇈",
    "uuml" to "ü",
    "uwangle" to "⦧",
    "vArr" to "⇕",
    "vBar" to "⫨",
    "vBarv" to "⫩",
    "vDash" to "⊨",
    "vangrt" to "⦜",
    "varepsilon" to "ϵ",
    "varkappa" to "ϰ",
    "varnothing" to "∅",
    "varphi" to "ϕ",
    "varpi" to "ϖ",
    "varpropto" to "∝",
    "varr" to "↕",
    "varrho" to "ϱ",
    "varsigma" to "ς",
    "varsubsetneq" to "⊊︀",
    "varsubsetneqq" to "⫋︀",
    "varsupsetneq" to "⊋︀",
    "varsupsetneqq" to "⫌︀",
    "vartheta" to "ϑ",
    "vartriangleleft" to "⊲",
    "vartriangleright" to "⊳",
    "vcy" to "в",
    "vdash" to "⊢",
    "vee" to "∨",
    "veebar" to "⊻",
    "veeeq" to "≚",
    "vellip" to "⋮",
    "verbar" to "|",
    "vert" to "|",
    "vfr" to "𝔳",
    "vltri" to "⊲",
    "vnsub" to "⊂⃒",
    "vnsup" to "⊃⃒",
    "vopf" to "𝕧",
    "vprop" to "∝",
    "vrtri" to "⊳",
    "vscr" to "𝓋",
    "vsubnE" to "⫋︀",
    "vsubne" to "⊊︀",
    "vsupnE" to "⫌︀",
    "vsupne" to "⊋︀",
    "vzigzag" to "⦚",
    "wcirc" to "ŵ",
    "wedbar" to "⩟",
    "wedge" to "∧",
    "wedgeq" to "≙",
    "weierp" to "℘",
    "wfr" to "𝔴",
    "wopf" to "𝕨",
    "wp" to "℘",
    "wr" to "≀",
    "wreath" to "≀",
    "wscr" to "𝓌",
    "xcap" to "⋂",
    "xcirc" to "◯",
    "xcup" to "⋃",
    "xdtri" to "▽",
    "xfr" to "𝔵",
    "xhArr" to "⟺",
    "xharr" to "⟷",
    "xi" to "ξ",
    "xlArr" to "⟸",
    "xlarr" to "⟵",
    "xmap" to "⟼",
    "xnis" to "⋻",
    "xodot" to "⨀",
    "xopf" to "𝕩",
    "xoplus" to "⨁",
    "xotime" to "⨂",
    "xrArr" to "⟹",
    "xrarr" to "⟶",
    "xscr" to "𝓍",
    "xsqcup" to "⨆",
    "xuplus" to "⨄",
    "xutri" to "△",
    "xvee" to "⋁",
    "xwedge" to "⋀",
    "yacute" to "ý",
    "yacy" to "я",
    "ycirc" to "ŷ",
    "ycy" to "ы",
    "yen" to "¥",
    "yfr" to "𝔶",
    "yicy" to "ї",
    "yopf" to "𝕪",
    "yscr" to "𝓎",
    "yucy" to "ю",
    "yuml" to "ÿ",
    "zacute" to "ź",
    "zcaron" to "ž",
    "zcy" to "з",
    "zdot" to "ż",
    "zeetrf" to "ℨ",
    "zeta" to "ζ",
    "zfr" to "𝔷",
    "zhcy" to "ж",
    "zigrarr" to "⇝",
    "zopf" to "𝕫",
    "zscr" to "𝓏",
    "zwj" to "‍",
    "zwnj" to "‌",
)







package edu.moravian.markdowneditor.android.markup

import androidx.compose.ui.text.AnnotatedString
import edu.moravian.markdowneditor.android.css.parseInlineCSS
import edu.moravian.markdowneditor.android.utilities.ComparablePair

/**
 * A node in a markup tree.
 */
data class MarkupNode(
    val tag: String,
    // Note: one of text or children should be null/empty (or both null/empty)
    val text: AnnotatedString? = null,
    val children: List<MarkupNode> = emptyList(),
    val attributes: Map<String, Any> = emptyMap(),
    val parent: MarkupNode? = null,
) {
    init { require(text === null || children.isEmpty()) { "MarkupNode cannot have both text and children" } }

    override fun toString(): String {
        val attr = attributes.entries.joinToString(" ") {
                (k, v) -> "${k}=${if (v is String) '"' + v + '"' else v}"
        }
        val open = if (attr.isEmpty()) "<$tag>" else "<$tag $attr>"
        return if (children.isNotEmpty()) {
            "$open\n${children.joinToString("\n").prependIndent("  ")}\n</$tag>"
        } else if (text !== null) { "$open${text.toTaggedString()}</$tag>" } else { open }
    }

    override fun hashCode(): Int {
        var result = tag.hashCode()
        result = 31 * result + (text?.hashCode() ?: 0)
        result = 31 * result + children.hashCode()
        result = 31 * result + attributes.hashCode()
        //result = 31 * result + parent.hashCode()  // would cause infinite recursion
        return result
    }

    override fun equals(other: Any?): Boolean =
        this === other || other is MarkupNode &&
            tag == other.tag && text != other.text && children != other.children &&
            attributes != other.attributes //&& parent != other.parent  // would cause infinite recursion
}

/** Convert an annotated string to a string with \[tag] [/tag] where there are string annotations */
private fun AnnotatedString.toTaggedString(): String {
    val all = getStringAnnotations(0, length)
    // TODO: this does not work for "instant" annotations
    val annotations = (
        all.mapIndexed { i, r -> Triple(r.toTag(), r.start, -i) } + 
        all.mapIndexedNotNull { i, r -> Triple("[/${r.tag}]", r.end, i).takeIf { r.start != r.end } }
    ).sortedBy { ComparablePair(-it.second, it.third) }
    val text = StringBuilder(this.text)
    for ((tag, location, _) in annotations) { text.insert(location, tag) }
    return text.toString()
}

private fun AnnotatedString.Range<String>.toTag() = "[$tag${if (item.isEmpty()) "" else " $item"}]"

inline val MarkupNode.siblings get() = parent?.children
inline val MarkupNode.isFirstOfParent get() = siblings?.firstOrNull() === this
inline val MarkupNode.isLastOfParent get() = siblings?.lastOrNull() === this
inline val MarkupNode.indexInParent get() = siblings?.indexOf(this) ?: -1
inline val MarkupNode.prevSibling get() = siblings?.let { s -> s.indexOf(this).takeIf { it > 0 }?.let { s[it-1] } }
inline val MarkupNode.nextSibling get() = siblings?.let { s -> s.indexOf(this).takeIf { it >= 0 && it < s.lastIndex }?.let { s[it+1] } }
inline val MarkupNode.parents get() = generateSequence(parent) { it.parent }
inline val MarkupNode.indexInParentOfTag get() = siblings?.filter { it.tag == tag }?.indexOf(this) ?: -1
inline fun MarkupNode.indexInParentOfTags(vararg tags: String) = siblings?.filter { it.tag in tags }?.indexOf(this) ?: -1

@Suppress("UNCHECKED_CAST")
val MarkupNode.styles: Map<String, String> get() {
    val style = attributes["style"]
    return if (style is String) { parseInlineCSS(style) }
        else { style as? Map<String, String> } ?: emptyMap()
}

fun MarkupNode.attrAsInt(attr: String) = attributes.valAsInt(attr)

internal fun Map<String, Any>.valAsInt(attr: String) =
    when (val raw = this[attr]) {
        is String -> raw.toIntOrNull()
        is Int? -> raw
        else -> null
    }

fun MarkupNode.attrAsBoolean(attr: String) = attributes.valAsBoolean(attr)

internal fun Map<String, Any>.valAsBoolean(attr: String) =
    when (val raw = this[attr]) {
        is String -> true // existence is true
        is Boolean -> raw
        else -> false
    }



package edu.moravian.markdowneditor.android.html

import androidx.compose.ui.text.AnnotatedString
import edu.moravian.markdowneditor.android.markup.MarkupNode
import edu.moravian.markdowneditor.android.utilities.attrs
import kotlin.math.max

fun MarkupNode.toHTML(): String {
    if (tag in specialTags) {
        return when (tag) {
            "#text" -> text?.toString()?.let { encodeHTMLEntities(it) } ?: ""
            "#cdata-section" -> "<![CDATA[${text?.toString()}]]>"
            "#comment" -> "<!--${attributes["data"]?.toString()?.replace("--", "__") ?: ""}-->"
            "#declaration" -> "<?${attributes["data"]?.toString() ?: ""}?>"
            "#processing-instruction" -> "<?${attributes["data"]?.toString() ?: ""}?>"
            else -> error("unknown special tag $tag")
        }
    }

    val attr = attributes.entries
        .filter { (k, v) -> !k.startsWith("*") && (v is String || v is Number || v is Boolean) }
        .joinToString(" ") { it.toAttribute() }
    val open = if (attr.isEmpty()) "<$tag>" else "<$tag $attr>"
    val children = this.children.filter { !it.tag.startsWith("*") }
    return if (children.isEmpty()) {
        if (text === null) open else "$open${text.toHTMLString()}</$tag>"
    } else {
        val contents = children.joinToString("\n") { it.toHTML() }
        "$open\n${contents.prependIndent("  ")}\n</$tag>"
    }
}

private fun AnnotatedString.toHTMLString(): String {
    val all = getStringAnnotations(0, length).filter { it.tag.firstOrNull() != '*' }

    // key: annotation location (start or end)
    // value: list of annotations at that position and their order (non-positive for starts, positive for ends)
    val allAnnotations = (
            all.mapIndexed { i, a -> Triple(a, a.start, -i) } +
            all.mapIndexed { i, a -> Triple(a, a.end, i+1) }
        ).groupBy({ (_, l, _) -> l }) { (a, _, i) -> a to i }


    var last = 0 // last processed position for text
    var skipUntil = 0
    val output = StringBuilder(text.length)
    for (index in allAnnotations.keys.sorted()) {
        // Add all text since the last annotation position
        output.appendHTML(text, max(last, skipUntil), index)

        // Go through all annotations at this position, sorted by their order
        val annotations = allAnnotations.getValue(index)
        for ((a, i) in annotations.sortedBy { -it.second }) {
            if (i <= 0) {
                when (a.tag) {
                    "#text" -> Unit // do nothing, let it process normally
                    "#comment" -> output.append("<!--${a.attrs["data"]?.replace("--", "__") ?: ""}-->")
                    "#declaration" -> output.append("<!${a.attrs["data"] ?: ""}>")
                    "#processing-instruction" -> output.append("<?${a.attrs["data"] ?: ""}?>")
                    "#cdata-section" -> {
                        output.append("<![CDATA[${text.substring(a.start, a.end)}]]>")
                        skipUntil = a.end
                    }
                    in tagHasAltText -> {
                        output.append(a.toTag(text.substring(a.start, a.end), true))
                        skipUntil = a.end
                    }
                    else -> output.append(a.toTag(close = a.start == a.end-1))
                }
            } else if (a.tag !in tagHasAltText && a.tag !in voidTags && a.tag !in specialTags) {
                output.append("</${a.tag}>")
            }
        }
        last = index
    }
    output.appendHTML(text, last)
    return output.toString()
}

private fun StringBuilder.appendHTML(text: String, start: Int = 0, end: Int = text.length) {
    append(encodeHTMLEntities(text.substring(start, end)).replace("\n", "<br>"))
}

private fun AnnotatedString.Range<String>.toTag(alt: String? = null, close: Boolean = false): String {
    val altAttr = alt?.let { " alt=\"${encodeHTMLEntities(it)}\"" } ?: ""
    val attrs = if (item.isEmpty()) "" else " " + attrs.entries
        .filter { (k, _) -> !k.startsWith("*") }
        .joinToString(" ") { it.toAttribute() }
    val end = if (close && tag !in voidTags) "/" else ""
    return "<$tag$attrs$altAttr$end>"
}

private val tagHasAltText = setOf("img")
private val specialTags = setOf("#cdata-section", "#comment", "#declaration", "#processing-instruction")

private fun Map.Entry<String, Any>.toAttribute(): String {
    val (key, value) = this
    val k = encodeHTMLEntities(key)
    val v = encodeHTMLEntities(value.toString())
    return when (value) {
        false -> ""
        true, "" -> k
        is String -> "$k=\"$v\""
        else -> "$k=$v"
    }
}
